### ISSUE TITLE
Dismantling runner bug

### ISSUE THREAD

**Issue by v3n0m3k** [tantinevincent/Onegai-oyodosan#18]
Dismantling runner doesn't work with lighter backgroud, have to change to smaller image.

Thanks for your hard work.

**Comment by tantinevincent** [comment]
Do you mean the "factory.png" ?

![factory](https://cloud.githubusercontent.com/assets/1463990/6096984/03f3aef6-afe6-11e4-97a5-9e077743bde5.png)

It can be quickly fix by changing image, 
maybe I will try to figure out the other solution.

Anyway, thank for your report.

**Comment by v3n0m3k** [comment]
Yeah, this one. Changed it already and it works like a charm.

**Comment by tantinevincent** [comment]
I've already tested new "factory.png" on two backgrounds,
please reopen this issue if someone get the same problem.
